In [ ]:
import jax
import jax.numpy as jnp
import numpy as np
import torch

In [ ]:
a1 = np.array([10,20])
b1 = np.array([30,40])
print (a1 + b1)

[40 60]


In [ ]:
a = jnp.array([10,20])
b = jnp.array([30,40])
print(a +b)

[40 60]


In [ ]:
print(a * b)

[300 800]


In [ ]:
x = torch.tensor([[10,20,30,40],[3,4,5,6], [4,5,6,7], [9,10,11,12]])
print(x)
print(x.shape)

tensor([[10, 20, 30, 40],
        [ 3,  4,  5,  6],
        [ 4,  5,  6,  7],
        [ 9, 10, 11, 12]])
torch.Size([4, 4])


In [ ]:
y = torch.tensor([ [1,2,3,4], [10,20, 30, 40], [1,2,3,4], [2,3,4,5] ])
print(y)

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 1,  2,  3,  4],
        [ 2,  3,  4,  5]])


In [ ]:
print (x * y)

tensor([[ 10,  40,  90, 160],
        [ 30,  80, 150, 240],
        [  4,  10,  18,  28],
        [ 18,  30,  44,  60]])


## Properties of the Identity Matrix

The **identity matrix** $I_n$ is a square $n \times n$ matrix with **1s on the main diagonal** and **0s everywhere else**.

$$
I_4 =
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

---

### Key Properties

| Property | Statement | Notes |
|---|---|---|
| **Multiplicative identity** | $A \cdot I = I \cdot A = A$ | Like multiplying a number by 1 |
| **Idempotent** | $I \cdot I = I^2 = I$ | Multiplying I by itself gives I |
| **Determinant** | $\det(I) = 1$ | Always exactly 1 |
| **Inverse** | $I^{-1} = I$ | I is its own inverse |
| **Transpose** | $I^T = I$ | I is its own transpose |
| **Eigenvalues** | All eigenvalues $= 1$ | Every vector is an eigenvector |
| **Trace** | $\text{tr}(I_n) = n$ | Sum of diagonal = size of matrix |
| **Rank** | $\text{rank}(I_n) = n$ | Full rank — no redundant rows/cols |

---

### Element-wise vs. Matrix Multiplication

There is an important distinction when working with the identity matrix:

- **Element-wise** (`A * I`): extracts the diagonal — zeros out all off-diagonal elements, leaving only diagonal values of `A`.
- **Matrix multiplication** (`A @ I`): returns `A` unchanged — the true multiplicative identity property.

```
Element-wise  A * I  →  diag(A)   (zeros off-diagonal)
Matrix mult   A @ I  →  A         (A unchanged)
```

### Why It Matters in Deep Learning

- **Weight initialisation:** initialising a weight matrix to $I$ helps preserve signal magnitude at the start of training.
- **Residual connections:** $\text{output} = x + f(x)$ can be written as $(I + W)x$ — the identity adds a direct gradient path.
- **Regularisation:** L2 regularisation adds $\lambda I$ to the Hessian, improving numerical stability.
- **Barlow Twins / VICReg:** the cross-correlation matrix is driven toward $I$ to prevent representational collapse.
- **Attention:** in self-attention, each token attending to itself corresponds to an identity-like attention pattern.

In [20]:
eye1 = torch.eye(4,4)
print(eye1)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [21]:
print(x * eye1)

NameError: name 'x' is not defined

In [ ]:
# Demonstrating identity matrix properties
import torch

A = torch.tensor([[10,20,30,40],[3,4,5,6],[4,5,6,7],[9,10,11,12]], dtype=torch.float32)
I = torch.eye(4)

# Property 1: Multiplicative identity  A @ I == A
print("A @ I == A:", torch.allclose(A @ I, A))
print("I @ A == A:", torch.allclose(I @ A, A))

# Property 2: Idempotent  I @ I == I
print("I @ I == I:", torch.allclose(I @ I, I))

# Property 3: Determinant == 1
print("det(I)   =", torch.linalg.det(I).item())

# Property 4: Inverse == I
print("inv(I) == I:", torch.allclose(torch.linalg.inv(I), I))

# Property 5: Transpose == I
print("I.T == I:", torch.allclose(I.T, I))

# Property 6: All eigenvalues == 1
eigvals = torch.linalg.eigvalsh(I)
print("Eigenvalues of I:", eigvals)

# Property 7: Trace == n
print("trace(I) =", torch.trace(I).item(), "  (n=4)")

# Element-wise vs matrix multiply comparison
print("\nElement-wise A * I (extracts diagonal):")
print(A * I)
print("\nMatrix multiply A @ I (returns A unchanged):")
print(A @ I)

A @ I == A: True
I @ A == A: True
I @ I == I: True
det(I)   = 1.0
inv(I) == I: True
I.T == I: True
Eigenvalues of I: tensor([1., 1., 1., 1.])
trace(I) = 4.0   (n=4)

Element-wise A * I (extracts diagonal):
tensor([[10.,  0.,  0.,  0.],
        [ 0.,  4.,  0.,  0.],
        [ 0.,  0.,  6.,  0.],
        [ 0.,  0.,  0., 12.]])

Matrix multiply A @ I (returns A unchanged):
tensor([[10., 20., 30., 40.],
        [ 3.,  4.,  5.,  6.],
        [ 4.,  5.,  6.,  7.],
        [ 9., 10., 11., 12.]])


In [ ]:
xyz = torch.linalg.det(eye1)
print(xyz)

tensor(1.)


In [ ]:
abcinv = torch.linalg.inv( torch.tensor([[10.0,20.0,30.0], [20.0,30.0,40.0], [200.0,300.0,400.0]]))
print(abcinv)
print(torch.linalg.inv(abcinv))


tensor([[-7.7717e-02, -1.3677e+06,  1.3677e+05],
        [-2.4457e-01,  2.7354e+06, -2.7354e+05],
        [ 2.2228e-01, -1.3677e+06,  1.3677e+05]])
tensor([[-4.6057,  0.6470,  6.4330],
        [ 4.9485,  7.4227,  9.8969],
        [49.4845, 74.2268, 98.9691]])


In [ ]:
A = torch.tensor([
    [10.,20.,30.],
    [20.,30.,40.],
    [200.,300.,400.]
])

print(torch.linalg.matrix_rank(A))
assert torch.linalg.matrix_rank(A) == A.shape[0], \
    f"Matrix is singular: rank={torch.linalg.matrix_rank(A)}, expected={A.shape[0]}"

O

tensor(2)


AssertionError: Matrix is singular: rank=2, expected=3

In [ ]:
def assert_invertible(A):
    rank = torch.linalg.matrix_rank(A)
    n = A.shape[0]
    assert rank == n, (
        f"Matrix is not invertible: rank={rank}, expected={n}"
    )

In [ ]:
assert_invertible(A)

AssertionError: Matrix is not invertible: rank=2, expected=3

The **rank of a matrix** is the **maximum number of linearly independent rows or columns** in the matrix.

Another way to say it is:

> **Rank = the dimension of the vector space spanned by the rows (or columns).**

The row rank and column rank are always equal, so we simply call it the **rank**.

### Intuition

Imagine each row of a matrix as a vector.

* If a row can be written as a combination of other rows, it **doesn't add new information**.
* Only rows that contribute new directions increase the rank.

For example,

```text
[1 2]
[2 4]
```

The second row is

```text
2 × [1 2]
```

so it adds no new information.

Therefore,

```text
rank = 1
```

---

### Example 1: Full rank

```text
A =
[1 0]
[0 1]
```

The rows are independent.

```
rank = 2
```

This matrix is invertible.

---

### Example 2: Rank 2

```text
A =
[1 2 3]
[4 5 6]
[5 7 9]
```

Notice

```text
Row3 = Row1 + Row2
```

Only two independent rows exist.

```
rank = 2
```

---

### Your example

```text
A =
[10  20  30]
[20  30  40]
[200 300 400]
```

Observe

```text
Row3 = 10 × Row2
```

So Row3 contributes nothing new.

The first two rows are independent, so

```text
rank = 2
```

PyTorch confirms this:

```python
import torch

A = torch.tensor([
    [10.,20.,30.],
    [20.,30.,40.],
    [200.,300.,400.]
])

print(torch.linalg.matrix_rank(A))
```

Output:

```text
tensor(2)
```

---

### Why is rank important?

For an (n \times n) matrix:

| Rank  | Meaning                         | Invertible? |
| ----- | ------------------------------- | ----------- |
| (n)   | Full rank                       | ✅ Yes       |
| (< n) | Some rows/columns are dependent | ❌ No        |

For your (3 \times 3) matrix:

* Rank = 2
* Expected full rank = 3
* Therefore, the matrix is **singular** and **cannot be inverted**.

---

### Geometric intuition

Think of the rows as directions in space:

* **Rank 1** → all rows lie on a **line**.
* **Rank 2** → all rows lie in a **plane**.
* **Rank 3** → rows span the full **3D space**.

For your matrix:

```
Row1  ↗
Row2    ↗    (different direction)
Row3 = 10 × Row2
```

Only two independent directions exist, so the rows span a **plane**, not the full 3D space. Hence, the rank is **2**.
