# Deep Learning Book — Mathematical Notation in Action

This notebook demonstrates every symbol from the *Deep Learning* book notation guide
(Goodfellow, Bengio & Courville) using **NumPy** and **PyTorch**.

Sections:
1. Numbers and Arrays
2. Sets and Graphs
3. Indexing
4. Linear Algebra Operations
5. Calculus
6. Probability and Information Theory
7. Functions
8. Datasets and Distributions

In [1]:
import numpy as np
import torch
import torch.nn.functional as F
import math

torch.manual_seed(42)
np.random.seed(42)
print('NumPy:', np.__version__)
print('PyTorch:', torch.__version__)

NumPy: 2.2.4
PyTorch: 2.6.0


---
## 1. Numbers and Arrays

| Symbol | Meaning |
|--------|---------|
| *a* (italic) | A scalar (integer or real) |
| **a** (bold lower) | A vector |
| ***A*** (bold upper) | A matrix |
| **A** (sans-serif) | A tensor |
| **I**_n | Identity matrix n×n |
| **e**^(i) | Standard basis vector (1 at position i) |
| diag(**a**) | Diagonal matrix from vector **a** |

In [2]:
# ── Scalar: a ─────────────────────────────────────────────────────
a = 3.14          # a scalar (float)
n = 5             # a scalar (integer)
print(f"Scalar a = {a},  n = {n}")

# ── Vector: bold a ────────────────────────────────────────────────
a_vec = np.array([1.0, 2.0, 3.0, 4.0])      # bold a  (NumPy)
a_t   = torch.tensor([1.0, 2.0, 3.0, 4.0]) # bold a  (PyTorch)
print(f"\nVector a = {a_vec}  shape={a_vec.shape}")

# ── Matrix: bold A ────────────────────────────────────────────────
A_mat = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype=float)   # bold A
print(f"\nMatrix A =\n{A_mat}  shape={A_mat.shape}")

# ── Tensor: sans-serif A ──────────────────────────────────────────
# A 3-D tensor (e.g. batch × height × width of feature maps)
A_tensor = torch.randn(2, 3, 4)   # sans-serif A
print(f"\nTensor A shape = {A_tensor.shape}   (batch=2, rows=3, cols=4)")

# ── Identity matrix I_n ───────────────────────────────────────────
I_3 = np.eye(3)          # I_3: 3×3 identity
I_t = torch.eye(4)       # I_4: 4×4 identity (PyTorch)
print(f"\nI_3 =\n{I_3}")

# ── Standard basis vector e^(i) ───────────────────────────────────
# e^(2): one-hot vector with 1 at position 2 (0-indexed)
def standard_basis(i, n):
    """e^(i): standard basis vector with 1 at position i."""
    e = np.zeros(n)
    e[i] = 1.0
    return e

e2 = standard_basis(2, 5)   # e^(2) in R^5
print(f"\ne^(2) in R^5 = {e2}")

# In PyTorch: one_hot
e2_torch = F.one_hot(torch.tensor(2), num_classes=5).float()
print(f"e^(2) torch  = {e2_torch.numpy()}")

# ── diag(a): diagonal matrix from vector ──────────────────────────
a_diag = np.array([2.0, 5.0, 3.0])
D = np.diag(a_diag)           # diag(a)
D_t = torch.diag(torch.tensor(a_diag))  # PyTorch
print(f"\ndiag(a) where a={a_diag}:\n{D}")

Scalar a = 3.14,  n = 5

Vector a = [1. 2. 3. 4.]  shape=(4,)

Matrix A =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]  shape=(3, 3)

Tensor A shape = torch.Size([2, 3, 4])   (batch=2, rows=3, cols=4)

I_3 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

e^(2) in R^5 = [0. 0. 1. 0. 0.]
e^(2) torch  = [0. 0. 1. 0. 0.]

diag(a) where a=[2. 5. 3.]:
[[2. 0. 0.]
 [0. 5. 0.]
 [0. 0. 3.]]


---
## 2. Sets and Graphs

| Symbol | Meaning |
|--------|---------|
| 𝔸 | A set |
| ℝ | The set of real numbers |
| {0,1} | Set containing 0 and 1 |
| {0,1,…,n} | All integers between 0 and n |
| [a,b] | Real interval including a and b |
| (a,b] | Real interval excluding a, including b |
| 𝔸\𝔹 | Set subtraction |
| 𝒢 | A graph |
| Pa𝒢(x_i) | Parents of x_i in 𝒢 |

In [3]:
# ── Sets in Python ────────────────────────────────────────────────
A_set = {1, 2, 3, 4, 5}       # 𝔸: a set
B_set = {3, 4, 5, 6, 7}       # 𝔹: another set

# ── ℝ — real numbers; represented as float64 in numpy ─────────────
x_real = np.float64(3.14159)   # x ∈ ℝ
print(f"x ∈ ℝ: {x_real}  (dtype={x_real.dtype})")

# ── {0,1} — binary set ────────────────────────────────────────────
binary_set = {0, 1}
print(f"\nbinary set {{0,1}} = {binary_set}")

# ── {0,1,...,n} — integer range ───────────────────────────────────
n = 5
integer_set = set(range(n + 1))   # {0,1,...,5}
print(f"{{0,1,...,{n}}} = {sorted(integer_set)}")

# ── [a,b] closed interval ─────────────────────────────────────────
a_iv, b_iv = 0.0, 1.0
# Sample uniformly from [a,b] (closed)
samples_closed = np.random.uniform(a_iv, b_iv, size=5)
print(f"\n5 samples from [{a_iv},{b_iv}] (uniform): {np.round(samples_closed,3)}")

# ── (a,b] half-open interval ──────────────────────────────────────
# np.clip demonstrates boundary handling
val = 0.0001
in_half_open = (val > a_iv) and (val <= b_iv)  # (a,b]
print(f"{val} ∈ ({a_iv},{b_iv}]: {in_half_open}")

# ── 𝔸\𝔹 — set difference ─────────────────────────────────────────
A_minus_B = A_set - B_set      # elements in A but not B
print(f"\n𝔸\\𝔹 = {A_set} \ {B_set} = {A_minus_B}")

# ── Graph 𝒢 — parent relationships ───────────────────────────────
# Simple DAG as adjacency dict: node → list of parents
graph_G = {
    'x1': [],          # root: no parents
    'x2': [],          # root
    'x3': ['x1'],      # parent: x1
    'x4': ['x1','x2'], # parents: x1, x2
    'x5': ['x3','x4'], # parents: x3, x4
}

def Pa_G(node, graph):
    """Pa_G(x_i): parents of node x_i in graph G."""
    return graph[node]

print(f"\nPa_G(x4) = {Pa_G('x4', graph_G)}")
print(f"Pa_G(x5) = {Pa_G('x5', graph_G)}")
print(f"Pa_G(x1) = {Pa_G('x1', graph_G)}  (root node, no parents)")

x ∈ ℝ: 3.14159  (dtype=float64)

binary set {0,1} = {0, 1}
{0,1,...,5} = [0, 1, 2, 3, 4, 5]

5 samples from [0.0,1.0] (uniform): [0.375 0.951 0.732 0.599 0.156]
0.0001 ∈ (0.0,1.0]: True

𝔸\𝔹 = {1, 2, 3, 4, 5} \ {3, 4, 5, 6, 7} = {1, 2}

Pa_G(x4) = ['x1', 'x2']
Pa_G(x5) = ['x3', 'x4']
Pa_G(x1) = []  (root node, no parents)


---
## 3. Indexing

| Symbol | Meaning |
|--------|---------|
| a_i | Element i of vector **a** (1-indexed) |
| a_{-i} | All elements except element i |
| A_{i,j} | Element (i,j) of matrix **A** |
| **A**_{i,:} | Row i of matrix **A** |
| **A**_{:,i} | Column i of matrix **A** |
| A_{i,j,k} | Element (i,j,k) of 3-D tensor **A** |
| **A**_{:,:,i} | 2-D slice of 3-D tensor at index i |
| a_i | Element i of random vector **a** |

In [4]:
import numpy as np
import torch

# ── Vector indexing ───────────────────────────────────────────────
a = np.array([10.0, 20.0, 30.0, 40.0, 50.0])

# a_i: element i (book uses 1-based; Python uses 0-based → adjust)
i = 3                      # book: 3rd element
a_i = a[i - 1]             # Python 0-indexed: a[2]
print(f"a = {a}")
print(f"a_3 (1-indexed) = {a_i}")

# a_{-i}: all elements EXCEPT element i
a_minus_i = np.delete(a, i - 1)   # remove index i-1
print(f"a_{{-3}} = {a_minus_i}   (all except 3rd)")

# ── Matrix indexing ───────────────────────────────────────────────
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

# A_{i,j}: element at row i, col j (1-indexed → 0-indexed)
row, col = 2, 3            # book: row 2, col 3
A_ij = A[row-1, col-1]     # Python: A[1, 2]
print(f"\nA =\n{A}")
print(f"A_{{2,3}} = {A_ij}")

# A_{i,:}: row i of A
A_row2 = A[row-1, :]       # bold A_{2,:}
print(f"A_{{2,:}} = {A_row2}   (row 2)")

# A_{:,i}: column i of A
A_col3 = A[:, col-1]       # bold A_{:,3}
print(f"A_{{:,3}} = {A_col3}   (column 3)")

# ── 3-D tensor indexing ───────────────────────────────────────────
# Shape (2, 3, 4) — e.g. (batch, height, width)
A3 = torch.arange(24, dtype=torch.float).reshape(2, 3, 4)
print(f"\n3-D tensor A shape = {A3.shape}")

# A_{i,j,k}: single element
i, j, k = 1, 2, 3         # 1-indexed
A_ijk = A3[i-1, j-1, k-1] # Python 0-indexed
print(f"A_{{1,2,3}} = {A_ijk.item()}")

# A_{:,:,i}: 2-D slice at depth index i
slice_i = A3[:, :, k-1]    # bold A_{:,:,3}
print(f"A_{{:,:,3}} =\n{slice_i}   (2-D slice at depth k={k})")

a = [10. 20. 30. 40. 50.]
a_3 (1-indexed) = 30.0
a_{-3} = [10. 20. 40. 50.]   (all except 3rd)

A =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A_{2,3} = 6.0
A_{2,:} = [4. 5. 6.]   (row 2)
A_{:,3} = [3. 6. 9.]   (column 3)

3-D tensor A shape = torch.Size([2, 3, 4])
A_{1,2,3} = 6.0
A_{:,:,3} =
tensor([[ 2.,  6., 10.],
        [14., 18., 22.]])   (2-D slice at depth k=3)


---
## 4. Linear Algebra Operations

| Symbol | Meaning |
|--------|---------|
| **A**^⊤ | Transpose of matrix **A** |
| **A**^+ | Moore-Penrose pseudoinverse |
| **A** ⊙ **B** | Element-wise (Hadamard) product |
| det(**A**) | Determinant of **A** |

In [5]:
import numpy as np
import torch

A = np.array([[1., 2., 3.],
              [4., 5., 6.]])
B = np.array([[7., 8., 9.],
              [1., 2., 3.]])

# ── A^⊤: Transpose ────────────────────────────────────────────────
A_T = A.T           # numpy
A_T_t = torch.tensor(A).T  # PyTorch
print(f"A shape: {A.shape}")
print(f"A^⊤ shape: {A_T.shape}")
print(f"A^⊤ =\n{A_T}")

# Verify: (AB)^⊤ = B^⊤ A^⊤
C = A @ A.T          # (2×3) @ (3×2) = (2×2)  — square for transpose test
assert np.allclose(C.T, A @ A.T), "Transpose identity failed"  # trivial here

# ── A^+: Moore-Penrose Pseudoinverse ──────────────────────────────
# Useful when A is not square or not invertible
# If A has full column rank: A^+ = (A^⊤ A)^{-1} A^⊤
A_plus = np.linalg.pinv(A)    # shape: (3×2)
print(f"\nA^+ (pseudoinverse) shape: {A_plus.shape}")
print(f"A^+ =\n{np.round(A_plus, 4)}")

# Verify: A A^+ ≈ I (if A has full row rank)
I_approx = A @ A_plus
print(f"A A^+ ≈ I?\n{np.round(I_approx, 4)}")

# In PyTorch
A_plus_t = torch.linalg.pinv(torch.tensor(A))
print(f"\nPyTorch pinv matches: {np.allclose(A_plus, A_plus_t.numpy(), atol=1e-5)}")

# ── A ⊙ B: Hadamard (element-wise) product ────────────────────────
Hadamard = A * B      # numpy: element-wise *
Hadamard_t = torch.tensor(A) * torch.tensor(B)  # PyTorch
print(f"\nA ⊙ B (Hadamard product) =\n{Hadamard}")

# Real use case: gating in SwiGLU  (gate ⊙ value)
gate  = torch.tensor([0.8, 0.2, 0.9, 0.1])
value = torch.tensor([1.5, 2.0, 0.5, 3.0])
swiglu_out = F.silu(gate) * value   # SwiGLU: SiLU(xW1) ⊙ xW2
print(f"\nSwiGLU gate ⊙ value = {swiglu_out.numpy().round(4)}")

# ── det(A): Determinant ───────────────────────────────────────────
A_sq = np.array([[2., 1.],
                 [5., 3.]])
det_A = np.linalg.det(A_sq)
det_A_t = torch.linalg.det(torch.tensor(A_sq))
print(f"\nA_sq =\n{A_sq}")
print(f"det(A_sq) = {det_A:.4f}   (non-zero → invertible)")
print(f"det(A_sq) PyTorch = {det_A_t.item():.4f}")

# Singular matrix: det = 0
A_sing = np.array([[1., 2.], [2., 4.]])  # row 2 = 2 × row 1
print(f"\ndet(singular A) = {np.linalg.det(A_sing):.6f}   (≈ 0 → not invertible)")

A shape: (2, 3)
A^⊤ shape: (3, 2)
A^⊤ =
[[1. 4.]
 [2. 5.]
 [3. 6.]]

A^+ (pseudoinverse) shape: (3, 2)
A^+ =
[[-0.9444  0.4444]
 [-0.1111  0.1111]
 [ 0.7222 -0.2222]]
A A^+ ≈ I?
[[1. 0.]
 [0. 1.]]

PyTorch pinv matches: True

A ⊙ B (Hadamard product) =
[[ 7. 16. 27.]
 [ 4. 10. 18.]]

SwiGLU gate ⊙ value = [0.828  0.2199 0.3199 0.1575]

A_sq =
[[2. 1.]
 [5. 3.]]
det(A_sq) = 1.0000   (non-zero → invertible)
det(A_sq) PyTorch = 1.0000

det(singular A) = 0.000000   (≈ 0 → not invertible)


---
## 5. Calculus

| Symbol | Meaning |
|--------|---------|
| dy/dx | Derivative of y w.r.t. x |
| ∂y/∂x | Partial derivative |
| ∇_x y | Gradient of y w.r.t. **x** |
| ∇_X y | Matrix derivatives (Jacobian) |
| ∂f/∂**x** | Jacobian matrix J ∈ ℝ^{m×n} |
| ∇²_x f(**x**) or **H**(f)(**x**) | Hessian matrix |
| ∫ f(**x**)d**x** | Definite integral over domain |

In [6]:
import torch
import numpy as np

# ── dy/dx: Scalar derivative via PyTorch autograd ─────────────────
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2 * x + 1    # y = x² + 2x + 1
y.backward()               # dy/dx = 2x + 2
print(f"y = x² + 2x + 1 at x=3")
print(f"dy/dx = 2x + 2 = {x.grad.item()}   (expected: {2*3+2})")

# ── ∂y/∂x: Partial derivative (scalar function of vector input) ───
x_vec = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y_scalar = x_vec[0]**2 + x_vec[1]*x_vec[2]   # y = x₁² + x₂x₃
y_scalar.backward()
print(f"\ny = x₁² + x₂x₃")
print(f"∂y/∂x₁ = 2x₁ = {x_vec.grad[0].item()}   (expected: {2*1.0})")
print(f"∂y/∂x₂ = x₃  = {x_vec.grad[1].item()}   (expected: {3.0})")
print(f"∂y/∂x₃ = x₂  = {x_vec.grad[2].item()}   (expected: {2.0})")

# ── ∇_x y: Gradient (vector of all partial derivatives) ───────────
x_g = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
# f(x) = ||x||² = x₁² + x₂² + x₃²
f_x = (x_g ** 2).sum()
f_x.backward()
grad = x_g.grad        # ∇_x f = 2x
print(f"\n∇_x ||x||² = 2x:")
print(f"x = {x_g.detach().numpy()},  ∇_x f = {grad.numpy()}")

# ── ∂f/∂x: Jacobian matrix ────────────────────────────────────────
# f: ℝ³ → ℝ²   J ∈ ℝ^{2×3}
def f_vec(x):
    """f(x) = [x₁² + x₂,  x₂x₃]"""
    return torch.stack([x[0]**2 + x[1],  x[1]*x[2]])

x_j = torch.tensor([2.0, 3.0, 4.0])
J = torch.autograd.functional.jacobian(f_vec, x_j)
print(f"\nJacobian J = ∂f/∂x at x=[2,3,4]:")
print(J.numpy())
print(f"  J[0,:] = [2x₁, 1, 0] = [{2*2.0}, 1.0, 0.0]")
print(f"  J[1,:] = [0, x₃, x₂] = [0.0, {4.0}, {3.0}]")

# ── ∇²_x f (Hessian) ──────────────────────────────────────────────
def scalar_f(x):
    """f(x) = x₁² + 2x₁x₂ + 3x₂²"""
    return x[0]**2 + 2*x[0]*x[1] + 3*x[1]**2

x_h = torch.tensor([1.0, 2.0])
H = torch.autograd.functional.hessian(scalar_f, x_h)
print(f"\nHessian H(f)(x) = ∇²_x f:")
print(H.numpy())
print("  Expected: [[2, 2], [2, 6]]")

# ── ∫ f(x)dx: Numerical integration ──────────────────────────────
# ∫₀¹ x² dx = 1/3 ≈ 0.3333
x_int = np.linspace(0, 1, 10000)
dx    = x_int[1] - x_int[0]
integral = np.sum(x_int**2) * dx        # Riemann sum
print(f"\n∫₀¹ x² dx ≈ {integral:.6f}   (exact: {1/3:.6f})")

# ∫_{ℝ} 𝒩(x;0,1) dx = 1  (probability normalises to 1)
gaussian = lambda x: (1/np.sqrt(2*np.pi)) * np.exp(-x**2/2)
x_gauss  = np.linspace(-6, 6, 100000)
dx_g     = x_gauss[1] - x_gauss[0]
norm_int = np.sum(gaussian(x_gauss)) * dx_g
print(f"∫_ℝ 𝒩(x;0,1)dx ≈ {norm_int:.6f}   (should be 1.0)")

y = x² + 2x + 1 at x=3
dy/dx = 2x + 2 = 8.0   (expected: 8)

y = x₁² + x₂x₃
∂y/∂x₁ = 2x₁ = 2.0   (expected: 2.0)
∂y/∂x₂ = x₃  = 3.0   (expected: 3.0)
∂y/∂x₃ = x₂  = 2.0   (expected: 2.0)

∇_x ||x||² = 2x:
x = [1. 2. 3.],  ∇_x f = [2. 4. 6.]

Jacobian J = ∂f/∂x at x=[2,3,4]:
[[4. 1. 0.]
 [0. 4. 3.]]
  J[0,:] = [2x₁, 1, 0] = [4.0, 1.0, 0.0]
  J[1,:] = [0, x₃, x₂] = [0.0, 4.0, 3.0]

Hessian H(f)(x) = ∇²_x f:
[[2. 2.]
 [2. 6.]]
  Expected: [[2, 2], [2, 6]]

∫₀¹ x² dx ≈ 0.333383   (exact: 0.333333)
∫_ℝ 𝒩(x;0,1)dx ≈ 1.000000   (should be 1.0)


---
## 6. Probability and Information Theory

| Symbol | Meaning |
|--------|---------|
| a ⊥ b | a and b are independent |
| a ⊥ b \| c | Conditionally independent given c |
| P(a) | Probability distribution over discrete variable |
| p(a) | Probability density (continuous) |
| a ~ P | Random variable a has distribution P |
| 𝔼_{x~P}[f(x)] | Expectation of f(x) w.r.t. P |
| Var(f(x)) | Variance |
| Cov(f(x),g(x)) | Covariance |
| H(x) | Shannon entropy |
| D_KL(P‖Q) | KL divergence |
| 𝒩(x;μ,Σ) | Gaussian distribution |

In [7]:
import numpy as np
import torch
import torch.nn.functional as F
from torch.distributions import Normal, Categorical

# ── P(a): Discrete probability distribution ───────────────────────
# Token probabilities from an LLM softmax
logits = torch.tensor([2.0, 1.0, 0.5, 3.0, 0.1])
P = F.softmax(logits, dim=0)   # P(a): discrete dist over 5 tokens
print(f"P(a) = {P.numpy().round(4)}")
print(f"Σ P(a) = {P.sum().item():.6f}   (must be 1.0)")

# ── p(a): Continuous probability density (Gaussian) ───────────────
mu, sigma = 0.0, 1.0
dist = Normal(mu, sigma)      # 𝒩(x;μ,σ²) — Gaussian
x_sample = dist.sample((5,)) # a ~ p  (draw 5 samples)
print(f"\n5 samples a ~ 𝒩(0,1): {x_sample.numpy().round(4)}")

# p(x) at a specific point
x_eval = torch.tensor(0.0)
p_x    = dist.log_prob(x_eval).exp()
p_manual = (1/np.sqrt(2*np.pi)) * np.exp(-x_eval.item()**2 / 2)
print(f"p(0) = {p_x.item():.6f}   (manual: {p_manual:.6f})")

# ── 𝔼_{x~P}[f(x)]: Expectation ───────────────────────────────────
# E[x] for discrete distribution
values = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
E_x = (values * P).sum()   # 𝔼[x] = Σ x·P(x)
print(f"\n𝔼[x] = Σ x·P(x) = {E_x.item():.4f}")

# Monte Carlo estimate of E[f(x)] where x~𝒩(0,1), f(x)=x²
samples = Normal(0, 1).sample((100000,))
E_x2_mc = (samples**2).mean()   # MC estimate of E[x²] = Var(x) + E[x]² = 1
print(f"MC 𝔼_{'{x~𝒩(0,1)}'}[x²] ≈ {E_x2_mc.item():.4f}   (exact: 1.0)")

# ── Var(f(x)): Variance ───────────────────────────────────────────
# Var(x) = E[x²] - E[x]²
Var_P = (values**2 * P).sum() - ((values * P).sum())**2
print(f"\nVar(x) for discrete dist = {Var_P.item():.4f}")

# PyTorch: torch.var (sample variance)
data = torch.tensor([2.0, 4.0, 4.0, 4.0, 5.0, 5.0, 7.0, 9.0])
print(f"torch.var(data) = {data.var().item():.4f}   (unbiased)")
print(f"Manual: E[x²]-E[x]² = {(data**2).mean() - data.mean()**2:.4f}   (biased)")

# ── Cov(f(x),g(x)): Covariance ────────────────────────────────────
x_data = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
y_data = 2*x_data + torch.randn(5)*0.1   # y ≈ 2x (highly correlated)
cov_xy = torch.cov(torch.stack([x_data, y_data]))
print(f"\nCov(x, y) matrix:\n{cov_xy.numpy().round(4)}")
print(f"  Cov(x,x) = Var(x) ≈ {cov_xy[0,0].item():.4f}")
print(f"  Cov(x,y) ≈ {cov_xy[0,1].item():.4f}   (positive: x,y positively correlated)")

# ── H(x): Shannon Entropy ─────────────────────────────────────────
def entropy(p):
    """H(x) = -Σ p(x) log p(x)  (in nats)"""
    p = p[p > 0]
    return -(p * torch.log(p)).sum()

# Uniform distribution → maximum entropy
P_uniform = torch.ones(5) / 5
H_uniform = entropy(P_uniform)
H_max     = torch.log(torch.tensor(5.0))   # log(n) = max entropy for n outcomes
print(f"\nH(uniform over 5) = {H_uniform.item():.4f}   (max = log(5) = {H_max.item():.4f})")

# Peaked distribution → low entropy
P_peaked = torch.tensor([0.97, 0.01, 0.01, 0.005, 0.005])
H_peaked = entropy(P_peaked)
print(f"H(peaked) = {H_peaked.item():.4f}   (much lower)")

# ── D_KL(P‖Q): KL Divergence ──────────────────────────────────────
# D_KL(P‖Q) = Σ P(x) log(P(x)/Q(x))  ≥ 0
P_dist = torch.tensor([0.3, 0.4, 0.2, 0.1])
Q_dist = torch.tensor([0.25, 0.35, 0.25, 0.15])

# Manual
kl_manual = (P_dist * (P_dist / Q_dist).log()).sum()

# PyTorch F.kl_div expects log-probabilities for input
kl_torch  = F.kl_div(Q_dist.log(), P_dist, reduction='sum')

print(f"\nD_KL(P‖Q) = {kl_manual.item():.6f}   (PyTorch: {kl_torch.item():.6f})")
print(f"D_KL(P‖P) = {F.kl_div(P_dist.log(), P_dist, reduction='sum').item():.8f}   (should be 0)")

# ── 𝒩(x;μ,Σ): Multivariate Gaussian ──────────────────────────────
from torch.distributions import MultivariateNormal
mu_mv   = torch.tensor([0.0, 0.0])
Sigma   = torch.tensor([[1.0, 0.8], [0.8, 1.0]])  # covariance Σ (correlated)
mvn     = MultivariateNormal(mu_mv, Sigma)
samples_mv = mvn.sample((5,))
print(f"\n𝒩(x;μ,Σ) samples (5×):")
print(samples_mv.numpy().round(3))
log_prob_0 = mvn.log_prob(mu_mv)
print(f"log p(μ) = {log_prob_0.item():.4f}   (highest log-prob at the mean)")

P(a) = [0.2243 0.0825 0.05   0.6096 0.0335]
Σ P(a) = 1.000000   (must be 1.0)

5 samples a ~ 𝒩(0,1): [ 1.3525  0.6863 -0.3278  0.795   0.2815]
p(0) = 0.398942   (manual: 0.398942)

𝔼[x] = Σ x·P(x) = 2.1457
MC 𝔼_{x~𝒩(0,1)}[x²] ≈ 1.0063   (exact: 1.0)

Var(x) for discrete dist = 1.7022
torch.var(data) = 4.5714   (unbiased)
Manual: E[x²]-E[x]² = 4.0000   (biased)

Cov(x, y) matrix:
[[2.5    4.9654]
 [4.9654 9.8652]]
  Cov(x,x) = Var(x) ≈ 2.5000
  Cov(x,y) ≈ 4.9654   (positive: x,y positively correlated)

H(uniform over 5) = 1.6094   (max = log(5) = 1.6094)
H(peaked) = 0.1746   (much lower)

D_KL(P‖Q) = 0.022934   (PyTorch: 0.022934)
D_KL(P‖P) = 0.00000000   (should be 0)

𝒩(x;μ,Σ) samples (5×):
[[ 0.954  0.227]
 [ 0.479  0.111]
 [-0.816  0.236]
 [-1.876 -2.336]
 [-1.031 -1.923]]
log p(μ) = -1.3271   (highest log-prob at the mean)


---
## 7. Functions

| Symbol | Meaning |
|--------|---------|
| f : 𝔸 → 𝔹 | Function with domain 𝔸 and range 𝔹 |
| f ∘ g | Composition of f and g |
| f(**x**;**θ**) | Function of **x** parameterised by **θ** |
| log x | Natural logarithm |
| σ(x) | Logistic sigmoid 1/(1+exp(-x)) |
| ζ(x) | Softplus log(1+exp(x)) |
| \|\|**x**\|\|_p | L^p norm |
| \|\|**x**\|\| | L² norm |
| x⁺ | Positive part max(0,x) |
| **1**_{condition} | Indicator function |

In [8]:
import numpy as np
import torch
import torch.nn.functional as F

x_test = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

# ── f: 𝔸 → 𝔹  (a parameterised function f(x;θ)) ──────────────────
class LinearFunction:
    """f(x; θ) = θ₁x + θ₂  —  function of x parameterised by θ"""
    def __init__(self, theta):
        self.theta = theta           # θ = (w, b)
    def __call__(self, x):
        return self.theta[0] * x + self.theta[1]

theta = torch.tensor([2.0, 1.0])    # θ = (weight=2, bias=1)
f_theta = LinearFunction(theta)
print(f"f(x; θ=[2,1]) = 2x+1:")
print(f"  f({x_test.numpy()}) = {f_theta(x_test).numpy()}")

# ── f ∘ g: Function composition ───────────────────────────────────
g = lambda x: x**2          # g(x) = x²
f = torch.sigmoid            # f(x) = σ(x)
fog = lambda x: f(g(x))     # (f ∘ g)(x) = σ(x²)
print(f"\n(f ∘ g)(x) = σ(x²) at x={x_test.numpy()}:")
print(f"  {fog(x_test).numpy().round(4)}")

# ── log x: Natural logarithm ──────────────────────────────────────
x_pos = torch.tensor([0.1, 0.5, 1.0, 2.0, 10.0])
log_x = torch.log(x_pos)          # natural log (ln)
log2_x = torch.log2(x_pos)        # log base 2
print(f"\nln(x)   = {log_x.numpy().round(4)}")
print(f"log₂(x) = {log2_x.numpy().round(4)}")

# ── σ(x): Logistic sigmoid ────────────────────────────────────────
sigma_x = torch.sigmoid(x_test)   # σ(x) = 1 / (1 + exp(-x))
sigma_manual = 1.0 / (1.0 + torch.exp(-x_test))
print(f"\nσ(x) at {x_test.numpy()}:")
print(f"  {sigma_x.numpy().round(4)}")
print(f"  Range: (0,1); σ(0)={sigma_x[2].item():.4f}")
assert torch.allclose(sigma_x, sigma_manual)

# ── ζ(x): Softplus ────────────────────────────────────────────────
# ζ(x) = log(1 + exp(x))   smooth approximation to max(0,x)
softplus_x = F.softplus(x_test)
softplus_manual = torch.log(1 + torch.exp(x_test))
print(f"\nζ(x) softplus at {x_test.numpy()}:")
print(f"  {softplus_x.numpy().round(4)}")
print(f"  Note: ζ(x) ≈ x for large x; ζ(x) ≈ 0 for very negative x")

# Relationship: σ'(x) = σ(x)(1-σ(x)),   ζ'(x) = σ(x)
print(f"  ζ'(x) = σ(x): {torch.autograd.grad(softplus_x.sum(), x_test.requires_grad_(True))[0].detach().numpy().round(4)}")

# ── ||x||_p: L^p norms ───────────────────────────────────────────
v = torch.tensor([3.0, 4.0])     # classic 3-4-5 example
l1_norm = torch.norm(v, p=1)     # ||x||₁ = |3| + |4| = 7
l2_norm = torch.norm(v, p=2)     # ||x||₂ = √(9+16) = 5
linf    = torch.norm(v, p=float('inf'))  # ||x||_∞ = max(3,4) = 4
print(f"\nv = {v.numpy()}")
print(f"||v||₁ = {l1_norm.item():.4f}   (L1 norm)")
print(f"||v||  = ||v||₂ = {l2_norm.item():.4f}   (L2 norm, Euclidean)")
print(f"||v||_∞ = {linf.item():.4f}   (L∞ norm, max element)")

# Matrix Frobenius norm
A = torch.randn(3, 4)
fro = torch.norm(A, p='fro')   # ||A||_F = √(Σ A_{ij}²)
print(f"||A||_F (Frobenius) = {fro.item():.4f}")

# ── x⁺: Positive part  max(0,x)  ─────────────────────────────────
x_plus = torch.clamp(x_test, min=0.0)   # x⁺ = max(0,x)  = ReLU!
relu_x = F.relu(x_test)                  # same thing
print(f"\nx⁺ = max(0,x) = ReLU(x) at {x_test.numpy()}:")
print(f"  {x_plus.numpy()}")

# ── 1_{condition}: Indicator function ────────────────────────────
x_ind = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
# 1_{x>0}: indicator that x > 0
indicator = (x_ind > 0).float()   # 1.0 if condition true, 0.0 otherwise
print(f"\n1_{{x>0}} at {x_ind.numpy()}:")
print(f"  {indicator.numpy()}")

# Use case: Heaviside step function
# Also used in 'hard' attention: argmax as indicator
logits_ex = torch.tensor([0.1, 0.8, 0.05, 0.05])
argmax_idx = logits_ex.argmax()
hard_attn = (torch.arange(4) == argmax_idx).float()  # 1_{i=argmax}
print(f"\nHard attention 1_{{i=argmax}} = {hard_attn.numpy()}")

f(x; θ=[2,1]) = 2x+1:
  f([-2. -1.  0.  1.  2.]) = [-3. -1.  1.  3.  5.]

(f ∘ g)(x) = σ(x²) at x=[-2. -1.  0.  1.  2.]:
  [0.982  0.7311 0.5    0.7311 0.982 ]

ln(x)   = [-2.3026 -0.6931  0.      0.6931  2.3026]
log₂(x) = [-3.3219 -1.      0.      1.      3.3219]

σ(x) at [-2. -1.  0.  1.  2.]:
  [0.1192 0.2689 0.5    0.7311 0.8808]
  Range: (0,1); σ(0)=0.5000

ζ(x) softplus at [-2. -1.  0.  1.  2.]:
  [0.1269 0.3133 0.6931 1.3133 2.1269]
  Note: ζ(x) ≈ x for large x; ζ(x) ≈ 0 for very negative x


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

---
## 8. Datasets and Distributions

| Symbol | Meaning |
|--------|---------|
| p_data | Data generating distribution |
| p̂_data | Empirical distribution defined by training set |
| 𝕏 | A set of training examples |
| **x**^(i) | The i-th example (input) from a dataset |
| y^(i) or **y**^(i) | Target associated with **x**^(i) |
| **X** | m×n design matrix (x^(i) in row **X**_{i,:}) |

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

np.random.seed(0)
torch.manual_seed(0)

# ── 𝕏: Training set,  x^(i): i-th example ───────────────────────
# Simulate p_data: data from a mixture of two Gaussians
n_samples = 100
n_features = 4

# 𝕏 = design matrix of shape (m × n) = (100 × 4)
X = np.random.randn(n_samples, n_features)   # bold X (design matrix)
print(f"𝕏 (design matrix X) shape: {X.shape}   (m={n_samples} examples, n={n_features} features)")

# x^(i): i-th example = i-th row of X
i = 3
x_i = X[i, :]      # x^(3): row X_{3,:}
print(f"x^({i}) = X_{{{i},:}} = {x_i.round(4)}")

# ── y^(i): Target labels ──────────────────────────────────────────
# Binary classification: y ∈ {0,1}
true_weights = np.array([1.5, -2.0, 0.5, 1.0])
logits_data  = X @ true_weights + np.random.randn(n_samples) * 0.3
y = (logits_data > 0).astype(float)   # y^(i) ∈ {0,1}

print(f"\ny^(i) labels (first 10): {y[:10]}")
print(f"Class balance: {y.mean():.2%} positive")

# ── p̂_data: Empirical distribution ───────────────────────────────
# p̂_data puts mass 1/m on each training example
def p_hat_data(x_query, X_train, bandwidth=0.5):
    """Kernel density estimate of the empirical distribution."""
    m = X_train.shape[0]
    diffs = X_train - x_query[np.newaxis, :]    # (m × n)
    sq_dists = (diffs**2).sum(axis=1)           # (m,)
    weights = np.exp(-sq_dists / (2*bandwidth**2))
    return weights / weights.sum()

probs = p_hat_data(x_i, X)
print(f"\np̂_data at x^(3): top-5 nearest training examples:")
top5 = np.argsort(-probs)[:5]
print(f"  indices={top5}, probs={probs[top5].round(4)}")

# ── PyTorch Dataset/DataLoader (𝕏 in practice) ───────────────────
X_t = torch.tensor(X, dtype=torch.float32)
y_t = torch.tensor(y, dtype=torch.float32)

dataset    = TensorDataset(X_t, y_t)     # 𝕏 as a PyTorch Dataset
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

for batch_X, batch_y in dataloader:
    # batch_X[i]: x^(i) for i in the mini-batch
    # batch_y[i]: y^(i) for i in the mini-batch
    print(f"\nMini-batch: X shape={batch_X.shape},  y shape={batch_y.shape}")
    print(f"First example x^(0) in batch: {batch_X[0].numpy().round(4)}")
    print(f"First target  y^(0) in batch: {batch_y[0].item()}")
    break

# ── Full MLE: minimise -Σ log p(y^(i)|x^(i);θ) over 𝕏 ────────────
# This is the cross-entropy loss used to train all neural networks
class LogisticModel(torch.nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.linear = torch.nn.Linear(n_features, 1)

    def forward(self, x):
        return torch.sigmoid(self.linear(x).squeeze())

model     = LogisticModel(n_features)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
criterion = torch.nn.BCELoss()   # -Σ y log p + (1-y) log(1-p)

# 3 training steps on 𝕏
for step in range(3):
    pred = model(X_t)
    # MLE objective: maximise Σ log p(y^(i)|x^(i);θ)
    # = minimise -Σ log p(y^(i)|x^(i);θ)  = cross-entropy
    loss = criterion(pred, y_t)
    optimizer.zero_grad()
    loss.backward()   # ∇_θ L = Σᵢ ∇_θ [-log p(y^(i)|x^(i);θ)]
    optimizer.step()
    print(f"Step {step+1}: loss = {loss.item():.4f}")

---
## Summary: Symbol → PyTorch/NumPy mapping

| DL Book Symbol | Python / NumPy / PyTorch |
|---------------|--------------------------|
| *a* (scalar) | `a = 3.14` |
| **a** (vector) | `np.array([...])` or `torch.tensor([...])` |
| ***A*** (matrix) | `np.array([[...]])` or `torch.tensor([[...]])` |
| **A** (tensor) | `torch.randn(b, h, w)` |
| **I**_n | `np.eye(n)` / `torch.eye(n)` |
| **e**^(i) | `F.one_hot(torch.tensor(i), n)` |
| diag(**a**) | `np.diag(a)` / `torch.diag(a)` |
| **A**^⊤ | `A.T` / `A.transpose(0,1)` |
| **A**^+ | `np.linalg.pinv(A)` / `torch.linalg.pinv(A)` |
| **A** ⊙ **B** | `A * B` (element-wise) |
| det(**A**) | `np.linalg.det(A)` / `torch.linalg.det(A)` |
| ∇_x y | `y.backward()` → `x.grad` |
| ∂f/∂**x** (Jacobian) | `torch.autograd.functional.jacobian(f, x)` |
| ∇² f (Hessian) | `torch.autograd.functional.hessian(f, x)` |
| ∫ f(x)dx | `np.sum(f(x)) * dx` (Riemann) |
| σ(x) | `torch.sigmoid(x)` / `F.sigmoid(x)` |
| ζ(x) | `F.softplus(x)` |
| \|\|**x**\|\| | `torch.norm(x)` |
| x⁺ | `F.relu(x)` / `torch.clamp(x, min=0)` |
| **1**_{cond} | `(x > 0).float()` |
| H(x) entropy | `-(p * p.log()).sum()` |
| D_KL(P‖Q) | `F.kl_div(Q.log(), P, reduction='sum')` |
| 𝒩(x;μ,Σ) | `MultivariateNormal(mu, Sigma)` |
| 𝔼[f(x)] | `(f_x * probs).sum()` or MC: `f(samples).mean()` |
| Var(x) | `torch.var(x)` |
| Cov(x,y) | `torch.cov(torch.stack([x, y]))` |
| **X** (design matrix) | `torch.tensor(X)` shape `(m, n)` |
| **x**^(i) | `X[i, :]` (row i of design matrix) |