In [4]:
import torch

In [5]:
import numpy as np

In [ ]:
t1 = torch.tensor([[10,2], [20,4]])
print(t1)

In [ ]:
t2 = torch.zeros(3,5)
print(t2)

In [10]:
eye = torch.eye(4)
print(eye)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [12]:
full = torch.full((3,5), 5.0)
print(full)

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])


In [13]:
ones = torch.ones((5,5))
print(ones)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [15]:
arr = np.array([1.0,2,0])
print(arr)

t5 = torch.tensor(arr)
print(t5)

[1. 2. 0.]
tensor([1., 2., 0.], dtype=torch.float64)


In [16]:
print(t5.storage())

 1.0
 2.0
 0.0
[torch.storage.TypedStorage(dtype=torch.float64, device=cpu) of size 3]


/var/folders/5p/03kg52wj05n43f49jr6552dh0000gn/T/ipykernel_56486/2931651131.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(t5.storage())
