In [ ]:
import torch
import torch._numpy as tnp


In [10]:
a = torch.tensor([40.0, 80.0, 45.0])
print (a)

tensor([40., 80., 45.])


In [11]:
print(torch.softmax(a, dim=0))

tensor([4.2484e-18, 1.0000e+00, 6.3051e-16])


In [12]:
b = torch.tensor( [5.0, 10.0, 5.6])
print(torch.softmax(b, dim=0))


tensor([0.0066, 0.9813, 0.0120])
